/*
 * This file is generated by jOOQ.
 */
package fr.hop63.e_choppe.db.tables;


import fr.hop63.e_choppe.db.Keys;
import fr.hop63.e_choppe.db.Public;
import fr.hop63.e_choppe.db.tables.SaleEntry.SaleEntryPath;
import fr.hop63.e_choppe.db.tables.records.ItemFamilyRecord;

import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ItemFamily extends TableImpl<ItemFamilyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.item_family</code>
     */
    public static final ItemFamily ITEM_FAMILY = new ItemFamily();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ItemFamilyRecord> getRecordType() {
        return ItemFamilyRecord.class;
    }

    /**
     * The column <code>public.item_family.id</code>.
     */
    public final TableField<ItemFamilyRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("nextval('item_family_id'::regclass)"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.item_family.label</code>.
     */
    public final TableField<ItemFamilyRecord, String> LABEL = createField(DSL.name("label"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.item_family.description</code>.
     */
    public final TableField<ItemFamilyRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(4096), this, "");

    /**
     * The column <code>public.item_family.color</code>.
     */
    public final TableField<ItemFamilyRecord, String> COLOR = createField(DSL.name("color"), SQLDataType.CHAR(6), this, "");

    private ItemFamily(Name alias, Table<ItemFamilyRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ItemFamily(Name alias, Table<ItemFamilyRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.item_family</code> table reference
     */
    public ItemFamily(String alias) {
        this(DSL.name(alias), ITEM_FAMILY);
    }

    /**
     * Create an aliased <code>public.item_family</code> table reference
     */
    public ItemFamily(Name alias) {
        this(alias, ITEM_FAMILY);
    }

    /**
     * Create a <code>public.item_family</code> table reference
     */
    public ItemFamily() {
        this(DSL.name("item_family"), null);
    }

    public <O extends Record> ItemFamily(Table<O> path, ForeignKey<O, ItemFamilyRecord> childPath, InverseForeignKey<O, ItemFamilyRecord> parentPath) {
        super(path, childPath, parentPath, ITEM_FAMILY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ItemFamilyPath extends ItemFamily implements Path<ItemFamilyRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ItemFamilyPath(Table<O> path, ForeignKey<O, ItemFamilyRecord> childPath, InverseForeignKey<O, ItemFamilyRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ItemFamilyPath(Name alias, Table<ItemFamilyRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ItemFamilyPath as(String alias) {
            return new ItemFamilyPath(DSL.name(alias), this);
        }

        @Override
        public ItemFamilyPath as(Name alias) {
            return new ItemFamilyPath(alias, this);
        }

        @Override
        public ItemFamilyPath as(Table<?> alias) {
            return new ItemFamilyPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ItemFamilyRecord> getPrimaryKey() {
        return Keys.ITEM_FAMILY_PKEY;
    }

    private transient SaleEntryPath _saleEntry;

    /**
     * Get the implicit to-many join path to the <code>public.sale_entry</code>
     * table
     */
    public SaleEntryPath saleEntry() {
        if (_saleEntry == null)
            _saleEntry = new SaleEntryPath(this, null, Keys.SALE_ENTRY__SALE_ENTRY_FAMILY_FKEY.getInverseKey());

        return _saleEntry;
    }

    @Override
    public ItemFamily as(String alias) {
        return new ItemFamily(DSL.name(alias), this);
    }

    @Override
    public ItemFamily as(Name alias) {
        return new ItemFamily(alias, this);
    }

    @Override
    public ItemFamily as(Table<?> alias) {
        return new ItemFamily(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemFamily rename(String name) {
        return new ItemFamily(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemFamily rename(Name name) {
        return new ItemFamily(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemFamily rename(Table<?> name) {
        return new ItemFamily(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemFamily where(Condition condition) {
        return new ItemFamily(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemFamily where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemFamily where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemFamily where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemFamily where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemFamily where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemFamily where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ItemFamily where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemFamily whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ItemFamily whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
