/*
 * This file is generated by jOOQ.
 */
package fr.hop63.e_choppe.db.tables;


import fr.hop63.e_choppe.db.Indexes;
import fr.hop63.e_choppe.db.Keys;
import fr.hop63.e_choppe.db.Public;
import fr.hop63.e_choppe.db.tables.ItemFamily.ItemFamilyPath;
import fr.hop63.e_choppe.db.tables.Sale.SalePath;
import fr.hop63.e_choppe.db.tables.records.SaleEntryRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SaleEntry extends TableImpl<SaleEntryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.sale_entry</code>
     */
    public static final SaleEntry SALE_ENTRY = new SaleEntry();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SaleEntryRecord> getRecordType() {
        return SaleEntryRecord.class;
    }

    /**
     * The column <code>public.sale_entry.id</code>.
     */
    public final TableField<SaleEntryRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("nextval('sale_entry_id'::regclass)"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.sale_entry.sale</code>.
     */
    public final TableField<SaleEntryRecord, Integer> SALE = createField(DSL.name("sale"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.sale_entry.family</code>.
     */
    public final TableField<SaleEntryRecord, Integer> FAMILY = createField(DSL.name("family"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.sale_entry.items</code>.
     */
    public final TableField<SaleEntryRecord, Integer> ITEMS = createField(DSL.name("items"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.sale_entry.weight</code>.
     */
    public final TableField<SaleEntryRecord, Integer> WEIGHT = createField(DSL.name("weight"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.sale_entry.price</code>.
     */
    public final TableField<SaleEntryRecord, Integer> PRICE = createField(DSL.name("price"), SQLDataType.INTEGER, this, "");

    private SaleEntry(Name alias, Table<SaleEntryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SaleEntry(Name alias, Table<SaleEntryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.sale_entry</code> table reference
     */
    public SaleEntry(String alias) {
        this(DSL.name(alias), SALE_ENTRY);
    }

    /**
     * Create an aliased <code>public.sale_entry</code> table reference
     */
    public SaleEntry(Name alias) {
        this(alias, SALE_ENTRY);
    }

    /**
     * Create a <code>public.sale_entry</code> table reference
     */
    public SaleEntry() {
        this(DSL.name("sale_entry"), null);
    }

    public <O extends Record> SaleEntry(Table<O> path, ForeignKey<O, SaleEntryRecord> childPath, InverseForeignKey<O, SaleEntryRecord> parentPath) {
        super(path, childPath, parentPath, SALE_ENTRY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SaleEntryPath extends SaleEntry implements Path<SaleEntryRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SaleEntryPath(Table<O> path, ForeignKey<O, SaleEntryRecord> childPath, InverseForeignKey<O, SaleEntryRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SaleEntryPath(Name alias, Table<SaleEntryRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SaleEntryPath as(String alias) {
            return new SaleEntryPath(DSL.name(alias), this);
        }

        @Override
        public SaleEntryPath as(Name alias) {
            return new SaleEntryPath(alias, this);
        }

        @Override
        public SaleEntryPath as(Table<?> alias) {
            return new SaleEntryPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SALE_ENTRY_SALE);
    }

    @Override
    public UniqueKey<SaleEntryRecord> getPrimaryKey() {
        return Keys.SALE_ENTRY_PKEY;
    }

    @Override
    public List<ForeignKey<SaleEntryRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SALE_ENTRY__SALE_ENTRY_FAMILY_FKEY, Keys.SALE_ENTRY__SALE_ENTRY_SALE_FKEY);
    }

    private transient ItemFamilyPath _itemFamily;

    /**
     * Get the implicit join path to the <code>public.item_family</code> table.
     */
    public ItemFamilyPath itemFamily() {
        if (_itemFamily == null)
            _itemFamily = new ItemFamilyPath(this, Keys.SALE_ENTRY__SALE_ENTRY_FAMILY_FKEY, null);

        return _itemFamily;
    }

    private transient SalePath _sale;

    /**
     * Get the implicit join path to the <code>public.sale</code> table.
     */
    public SalePath sale() {
        if (_sale == null)
            _sale = new SalePath(this, Keys.SALE_ENTRY__SALE_ENTRY_SALE_FKEY, null);

        return _sale;
    }

    @Override
    public SaleEntry as(String alias) {
        return new SaleEntry(DSL.name(alias), this);
    }

    @Override
    public SaleEntry as(Name alias) {
        return new SaleEntry(alias, this);
    }

    @Override
    public SaleEntry as(Table<?> alias) {
        return new SaleEntry(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SaleEntry rename(String name) {
        return new SaleEntry(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SaleEntry rename(Name name) {
        return new SaleEntry(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SaleEntry rename(Table<?> name) {
        return new SaleEntry(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SaleEntry where(Condition condition) {
        return new SaleEntry(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SaleEntry where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SaleEntry where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SaleEntry where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SaleEntry where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SaleEntry where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SaleEntry where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SaleEntry where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SaleEntry whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SaleEntry whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
