/*
 * This file is generated by jOOQ.
 */
package fr.hop63.e_choppe.db.tables;


import fr.hop63.e_choppe.db.Indexes;
import fr.hop63.e_choppe.db.Keys;
import fr.hop63.e_choppe.db.Public;
import fr.hop63.e_choppe.db.tables.SaleEntry.SaleEntryPath;
import fr.hop63.e_choppe.db.tables.records.SaleRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sale extends TableImpl<SaleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.sale</code>
     */
    public static final Sale SALE = new Sale();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SaleRecord> getRecordType() {
        return SaleRecord.class;
    }

    /**
     * The column <code>public.sale.id</code>.
     */
    public final TableField<SaleRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("nextval('sale_id'::regclass)"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.sale.date</code>.
     */
    public final TableField<SaleRecord, LocalDateTime> DATE = createField(DSL.name("date"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    private Sale(Name alias, Table<SaleRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Sale(Name alias, Table<SaleRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.sale</code> table reference
     */
    public Sale(String alias) {
        this(DSL.name(alias), SALE);
    }

    /**
     * Create an aliased <code>public.sale</code> table reference
     */
    public Sale(Name alias) {
        this(alias, SALE);
    }

    /**
     * Create a <code>public.sale</code> table reference
     */
    public Sale() {
        this(DSL.name("sale"), null);
    }

    public <O extends Record> Sale(Table<O> path, ForeignKey<O, SaleRecord> childPath, InverseForeignKey<O, SaleRecord> parentPath) {
        super(path, childPath, parentPath, SALE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SalePath extends Sale implements Path<SaleRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SalePath(Table<O> path, ForeignKey<O, SaleRecord> childPath, InverseForeignKey<O, SaleRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SalePath(Name alias, Table<SaleRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SalePath as(String alias) {
            return new SalePath(DSL.name(alias), this);
        }

        @Override
        public SalePath as(Name alias) {
            return new SalePath(alias, this);
        }

        @Override
        public SalePath as(Table<?> alias) {
            return new SalePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SALE_DATE);
    }

    @Override
    public UniqueKey<SaleRecord> getPrimaryKey() {
        return Keys.SALE_PKEY;
    }

    private transient SaleEntryPath _saleEntry;

    /**
     * Get the implicit to-many join path to the <code>public.sale_entry</code>
     * table
     */
    public SaleEntryPath saleEntry() {
        if (_saleEntry == null)
            _saleEntry = new SaleEntryPath(this, null, Keys.SALE_ENTRY__SALE_ENTRY_SALE_FKEY.getInverseKey());

        return _saleEntry;
    }

    @Override
    public Sale as(String alias) {
        return new Sale(DSL.name(alias), this);
    }

    @Override
    public Sale as(Name alias) {
        return new Sale(alias, this);
    }

    @Override
    public Sale as(Table<?> alias) {
        return new Sale(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Sale rename(String name) {
        return new Sale(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sale rename(Name name) {
        return new Sale(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sale rename(Table<?> name) {
        return new Sale(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sale where(Condition condition) {
        return new Sale(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sale where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sale where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sale where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sale where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sale where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sale where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sale where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sale whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sale whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
