/*
 * This file is generated by jOOQ.
 */
package fr.hop63.e_choppe.db;


import fr.hop63.e_choppe.db.tables.Sale;
import fr.hop63.e_choppe.db.tables.SaleEntry;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SALE_DATE = Internal.createIndex(DSL.name("sale_date"), Sale.SALE, new OrderField[] { Sale.SALE.DATE }, false);
    public static final Index SALE_ENTRY_SALE = Internal.createIndex(DSL.name("sale_entry_sale"), SaleEntry.SALE_ENTRY, new OrderField[] { SaleEntry.SALE_ENTRY.SALE }, false);
}
