/*
 * This file is generated by jOOQ.
 */
package fr.hop63.e_choppe.db;


import fr.hop63.e_choppe.db.tables.ItemFamily;
import fr.hop63.e_choppe.db.tables.Sale;
import fr.hop63.e_choppe.db.tables.SaleEntry;
import fr.hop63.e_choppe.db.tables.records.ItemFamilyRecord;
import fr.hop63.e_choppe.db.tables.records.SaleEntryRecord;
import fr.hop63.e_choppe.db.tables.records.SaleRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ItemFamilyRecord> ITEM_FAMILY_PKEY = Internal.createUniqueKey(ItemFamily.ITEM_FAMILY, DSL.name("item_family_pkey"), new TableField[] { ItemFamily.ITEM_FAMILY.ID }, true);
    public static final UniqueKey<SaleRecord> SALE_PKEY = Internal.createUniqueKey(Sale.SALE, DSL.name("sale_pkey"), new TableField[] { Sale.SALE.ID }, true);
    public static final UniqueKey<SaleEntryRecord> SALE_ENTRY_PKEY = Internal.createUniqueKey(SaleEntry.SALE_ENTRY, DSL.name("sale_entry_pkey"), new TableField[] { SaleEntry.SALE_ENTRY.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<SaleEntryRecord, ItemFamilyRecord> SALE_ENTRY__SALE_ENTRY_FAMILY_FKEY = Internal.createForeignKey(SaleEntry.SALE_ENTRY, DSL.name("sale_entry_family_fkey"), new TableField[] { SaleEntry.SALE_ENTRY.FAMILY }, Keys.ITEM_FAMILY_PKEY, new TableField[] { ItemFamily.ITEM_FAMILY.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<SaleEntryRecord, SaleRecord> SALE_ENTRY__SALE_ENTRY_SALE_FKEY = Internal.createForeignKey(SaleEntry.SALE_ENTRY, DSL.name("sale_entry_sale_fkey"), new TableField[] { SaleEntry.SALE_ENTRY.SALE }, Keys.SALE_PKEY, new TableField[] { Sale.SALE.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
}
