/*
 * This file is generated by jOOQ.
 */
package fr.hop63.e_choppe.db;


import fr.hop63.e_choppe.db.tables.ItemFamily;
import fr.hop63.e_choppe.db.tables.Sale;
import fr.hop63.e_choppe.db.tables.SaleEntry;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * standard public schema
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.item_family</code>.
     */
    public final ItemFamily ITEM_FAMILY = ItemFamily.ITEM_FAMILY;

    /**
     * The table <code>public.sale</code>.
     */
    public final Sale SALE = Sale.SALE;

    /**
     * The table <code>public.sale_entry</code>.
     */
    public final SaleEntry SALE_ENTRY = SaleEntry.SALE_ENTRY;

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment("standard public schema"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ItemFamily.ITEM_FAMILY,
            Sale.SALE,
            SaleEntry.SALE_ENTRY
        );
    }
}
