/*
 * This file is generated by jOOQ.
 */
package fr.hop63.e_choppe.db;


import fr.hop63.e_choppe.db.tables.ItemFamily;
import fr.hop63.e_choppe.db.tables.Sale;
import fr.hop63.e_choppe.db.tables.SaleEntry;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.item_family</code>.
     */
    public static final ItemFamily ITEM_FAMILY = ItemFamily.ITEM_FAMILY;

    /**
     * The table <code>public.sale</code>.
     */
    public static final Sale SALE = Sale.SALE;

    /**
     * The table <code>public.sale_entry</code>.
     */
    public static final SaleEntry SALE_ENTRY = SaleEntry.SALE_ENTRY;
}
