/*
 * This file is generated by jOOQ.
 */
package fr.hop63.e_choppe.db.tables.records;


import fr.hop63.e_choppe.db.tables.ItemFamily;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ItemFamilyRecord extends UpdatableRecordImpl<ItemFamilyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.item_family.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.item_family.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.item_family.label</code>.
     */
    public void setLabel(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.item_family.label</code>.
     */
    public String getLabel() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.item_family.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.item_family.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.item_family.color</code>.
     */
    public void setColor(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.item_family.color</code>.
     */
    public String getColor() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemFamilyRecord
     */
    public ItemFamilyRecord() {
        super(ItemFamily.ITEM_FAMILY);
    }

    /**
     * Create a detached, initialised ItemFamilyRecord
     */
    public ItemFamilyRecord(Integer id, String label, String description, String color) {
        super(ItemFamily.ITEM_FAMILY);

        setId(id);
        setLabel(label);
        setDescription(description);
        setColor(color);
        resetTouchedOnNotNull();
    }
}
