/*
 * This file is generated by jOOQ.
 */
package fr.hop63.e_choppe.db.tables.records;


import fr.hop63.e_choppe.db.tables.SaleEntry;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SaleEntryRecord extends UpdatableRecordImpl<SaleEntryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.sale_entry.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.sale_entry.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.sale_entry.sale</code>.
     */
    public void setSale(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.sale_entry.sale</code>.
     */
    public Integer getSale() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.sale_entry.family</code>.
     */
    public void setFamily(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.sale_entry.family</code>.
     */
    public Integer getFamily() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.sale_entry.items</code>.
     */
    public void setItems(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.sale_entry.items</code>.
     */
    public Integer getItems() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.sale_entry.weight</code>.
     */
    public void setWeight(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.sale_entry.weight</code>.
     */
    public Integer getWeight() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.sale_entry.price</code>.
     */
    public void setPrice(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.sale_entry.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SaleEntryRecord
     */
    public SaleEntryRecord() {
        super(SaleEntry.SALE_ENTRY);
    }

    /**
     * Create a detached, initialised SaleEntryRecord
     */
    public SaleEntryRecord(Integer id, Integer sale, Integer family, Integer items, Integer weight, Integer price) {
        super(SaleEntry.SALE_ENTRY);

        setId(id);
        setSale(sale);
        setFamily(family);
        setItems(items);
        setWeight(weight);
        setPrice(price);
        resetTouchedOnNotNull();
    }
}
